In [ ]:
!nvidia-smi

Wed Sep  4 15:44:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


# Introduction to Tensors

## Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

In [ ]:
TENSOR[0,1,2]

tensor(9)

### Random Tensors

Why random tensors?

Random tensors are important as the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7888, 0.1789, 0.0323, 0.3035],
        [0.6505, 0.5286, 0.2685, 0.7418],
        [0.3422, 0.4886, 0.3932, 0.5232]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor1 = torch.rand(2,3,4)
random_tensor1

tensor([[[0.8096, 0.2705, 0.8371, 0.7421],
         [0.1707, 0.6894, 0.5737, 0.5443],
         [0.9103, 0.3300, 0.6641, 0.5194]],

        [[0.5735, 0.4729, 0.0585, 0.6837],
         [0.6927, 0.1921, 0.8446, 0.1810],
         [0.6191, 0.5678, 0.1800, 0.6280]]])

In [ ]:
random_tensor1.ndim

3

In [ ]:
random_tensor1.shape

torch.Size([2, 3, 4])

In [ ]:
# Create a random tensor with similar shape tp an image tensor
radom_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
radom_image_size_tensor.shape, radom_image_size_tensor.ndim
(torch.Size([224, 224, 3]), 3)

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# check the datatype of a tensor
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
im = torch.arange(60).reshape(3,4,5)
im.reshape(4,5,-1)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],

        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35],
         [36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]]])

In [ ]:
torch.arange(start=1, end=1000, step=73)

tensor([  1,  74, 147, 220, 293, 366, 439, 512, 585, 658, 731, 804, 877, 950])

In [ ]:
# Creating tensors like
# to create tensors shaped like some other tensors
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,# what datatype is the tensor (e.g. float32 or float16)
                               device=None,# what device is your tensor on
                               requires_grad=False)# whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
product = float_16_tensor * float_32_tensor

In [ ]:
product.dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
product = int_32_tensor * float_32_tensor
product.dtype, product

(torch.float32, tensor([ 9., 36., 81.]))

### Getting information from tensors

1. Tensors not right datatype - to get datatype , can use tensor.dtype
2. Tensors not right shape - can use tensor.shape
3. Tensors not on right device - can use tensor.device


In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4703, 0.7571, 0.3633, 0.7466],
        [0.9572, 0.9709, 0.1540, 0.3297],
        [0.3832, 0.4955, 0.2673, 0.1046]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4703, 0.7571, 0.3633, 0.7466],
        [0.9572, 0.9709, 0.1540, 0.3297],
        [0.3832, 0.4955, 0.2673, 0.1046]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
x = torch.rand(size=(3,4), dtype=torch.float16, device="cpu")

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multipication (element wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3], dtype=torch.int8)
tensor + 10

tensor([11, 12, 13], dtype=torch.int8)

In [ ]:
tensor.type(torch.float32)

tensor([1., 2., 3.])

In [ ]:
tensor * 10

tensor([10, 20, 30], dtype=torch.int8)

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30], dtype=torch.int8)

In [ ]:
torch.add(tensor, 20)

tensor([21, 22, 23], dtype=torch.int8)

### Matrix Multiplication

In [ ]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9], dtype=torch.int8)

In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14, dtype=torch.int8)

### One of the most common errors in deep learning , Shape errors

In [ ]:
torch.matmul(torch.rand(size=(3,2)), torch.rand(size=(3,2)))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(size=(3,2)), torch.rand(size=(2,3)))

tensor([[0.5101, 0.8254, 0.7111],
        [0.8661, 1.0631, 1.0404],
        [0.4708, 0.5238, 0.5389]])

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
# torch.mm is same as torch.matmul
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our shape issue we will manipulate the shape of one of our tensors.
A **transpose** switches the axes or dimensions of given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# The matrix multiplication works when we transpose one of the matrices
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, sum, mean etc (tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin(), x[0]

(tensor(0), tensor(0))

In [ ]:
x.argmax(), x[9]

(tensor(9), tensor(90))

In [ ]:
y = torch.tensor([[1,2,3],[7,6,5],[7,5,9]])
y

tensor([[1, 2, 3],
        [7, 6, 5],
        [7, 5, 9]])

In [ ]:
torch.argmin(y,dim=0), torch.argmin(y,dim=1)

(tensor([0, 0, 0]), tensor([0, 2, 1]))

### Reshaping, Stacking ,Squeezing and Unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of input tensor of certain shape but keep same memory as original tensor
* Stacking -
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
# shares the same memory with original memory
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# changing z will change the original tensor
z[:,0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
# torch.squeeze
x_reshaped

tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_reshaped.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze - adds a single dimension to a target tensor at a specific dim
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor
x = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
x.shape

torch.Size([224, 224, 3])

In [ ]:
# permute the original tensor to rearrange the axis (or dim) order
# now the below will be color channel, height, width
torch.permute(x, (2,0,1)).shape # shifts axis 0->1, 1->2, 2->0

torch.Size([3, 224, 224])

### Indexing
Similar to NumPy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Indexing on the zeroth dimension
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# index on last dimension
x[0][0][0]

tensor(1)

In [ ]:
# We can also use : to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
import torch
x = torch.arange(9).reshape(1,3,3)
x[:,:,2]

tensor([[2, 5, 8]])

## Pytorch tensors and numpy

Pytorch has functionality to interact with numppy

* Data in numpy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor to numpy -> torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
# see when we create tensor defalt dtype is different from when creating from numpy array
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# so we may do this to keep dtype as torch.float32
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [ ]:
# change the value of array, will this change the value of the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to numpy
# see the dtype of numpy array is float32 as default of torch is torch.float32
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> update random numbers to fit data -> again -> again...`

To reduce the randomness in PyTorch comes the concept of **random seed.**

Essentially what the random seed does is "flavour" the randomness

In [ ]:
# each time we will get different numbers on running cell
torch.rand(size=(3,3))

tensor([[0.7113, 0.3418, 0.4291],
        [0.1115, 0.4508, 0.5825],
        [0.6767, 0.3088, 0.3243]])

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1896, 0.6686, 0.4104, 0.4975],
        [0.6430, 0.8611, 0.2005, 0.4380],
        [0.2667, 0.2589, 0.2078, 0.5882]])
tensor([[0.2813, 0.3368, 0.2936, 0.2032],
        [0.7048, 0.1493, 0.5949, 0.1987],
        [0.3028, 0.4748, 0.9727, 0.7170]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducable tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducable tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects no GPUs (making faster computations)

GPU's = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good


### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure.

In [ ]:
!nvidia-smi

Sun Sep 15 11:56:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running on both gpu or cpu, it's best practice to set up device agnostic code eg. run on gpu if available else default to cpu

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count the number of devices (GPU's)
torch.cuda.device_count()

1

### 3. Putting tesnsors and model on the GPU is because usinng GPU results in faster computations

In [ ]:
# Create a tensor (default is on CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor = torch.tensor([1,2,3])

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor on GPU, can't transform it to Numpy
# Numpy works with CPU
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with Numpy issue , we can first set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
torch.manual_seed(1234)
ten1 = torch.rand(2,3)
ten2 = torch.rand(2,3)

In [ ]:
ten1.device, ten2.device

(device(type='cpu'), device(type='cpu'))

### In-place operations Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x

In [ ]:
tensor = torch.zeros(size=(3,3))
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


### If we perform inplace operations on a tensor and we have created a numpy array using that then the changes will reflect in numpy tensor and vice versa

In [ ]:
import torch
import numpy as np
tensor = torch.ones(5)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor.add_(10)
tensor, numpy_tensor

(tensor([11., 11., 11., 11., 11.]),
 array([11., 11., 11., 11., 11.], dtype=float32))

In [ ]:
# similarly
numpy_tensor = np.ones(5)
tensor = torch.from_numpy(numpy_tensor)
numpy_tensor, tensor

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [ ]:
np.add(numpy_tensor, 5, out = numpy_tensor)
numpy_tensor, tensor

(array([6., 6., 6., 6., 6.]),
 tensor([6., 6., 6., 6., 6.], dtype=torch.float64))

### End

In [ ]:
ten1 = ten1.to(device)
ten2 = ten2.to(device)

In [ ]:
ten1,ten2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [ ]:
import torch
t1 = torch.rand(2,3)
t2 = torch.rand(3,2)
t3 = torch.empty(3, 5)
torch.mm(t1, t2, out = t3),t3

<ipython-input-7-a1542d8daf72>:5: UserWarning: An output with one or more elements was resized since it had shape [3, 5], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.mm(t1, t2, out = t3),t3


(tensor([[0.8949, 1.4787],
         [0.9532, 1.2193]]),
 tensor([[0.8949, 1.4787],
         [0.9532, 1.2193]]))

In [ ]:
n1 = t1.numpy()
print(n1,'\n',t1)
torch.add(t1,10)
print(n1,'\n',t1)

[[0.9381694  0.59840155 0.33661854]
 [0.9174917  0.1225031  0.6469803 ]] 
 tensor([[0.9382, 0.5984, 0.3366],
        [0.9175, 0.1225, 0.6470]])
[[0.9381694  0.59840155 0.33661854]
 [0.9174917  0.1225031  0.6469803 ]] 
 tensor([[0.9382, 0.5984, 0.3366],
        [0.9175, 0.1225, 0.6470]])
